mysql:
    image: mysql:5.6.30
    environment:
        - MYSQL_ROOT_PASSWORD=Imix2016
        - MYSQL_DATABASE=jira
        - MYSQL_USER=jira
        - MYSQL_PASSWORD=Imix2016
        - TZ=America/Bogota
    ports:
        - 3306:3306
    expose:
        - 3306
    volumes:
        - /home/jira/var/lib/mysql:/var/lib/mysql
    command:
        - --character-set-server=utf8
        - --collation-server=utf8_bin
        - --lower_case_table_names=1
